basic-rails/scheting/config/routes.rb
Rails.application.routes.draw do

  resources :rooms, :meetings
  root to: 'rooms#index'

end

basic-rails/scheting/app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

    user ||= User.new # guest user (not logged in)

    if user.persisted?
      can :manage, Room
      can :read, Meeting
      can :manage, Meeting, user_id: user.id
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

basic-rails/scheting/app/models/meeting.rb
require 'date'

class Meeting < ActiveRecord::Base
  MEETING_MAXIMUM_DURATION = 7200
  MEETING_MINIMUM_DURATION = 600

  belongs_to :user
  belongs_to :room

  validate :room_available
  validate :beggining_before_end
  validate :duration_limits
  validates :title, :begins, :ends, :user_id, :room_id , presence: true

  scope :between_dates, -> (begin_date, end_date) { where("(begins between ? and ?) or (ends between ? and ?)", begin_date, end_date, begin_date, end_date) }

  def self.by_date
    order(:begins)
  end

  private

  def duration_limits
    if (ends - begins) > MEETING_MAXIMUM_DURATION
      errors.add(:base, "The maximum duration for a meeting is 2 hours")
    elsif (ends - begins) < MEETING_MINIMUM_DURATION
      errors.add(:base, "The minimum duration for a meeting is 10 minutes")
    end
  end

  def beggining_before_end
    if begins > ends
      errors.add(:base, "The begin date must be before the end date")
    end
  end

  def room_available
    occupied = room.occupied?(begins, ends) { |meetings| meetings.where('id != ?', id) }

    if occupied
      errors.add(:base, "The room is occupied for that period")
    end
  end
end

basic-rails/scheting/app/models/room.rb
class Room < ActiveRecord::Base
  has_many :meetings

  validates :name, presence: true

  def occupied?(begin_date, end_date)
    all_meetings_in_range = meetings.between_dates(begin_date, end_date)

    filtered_meetings = if block_given?
      yield all_meetings_in_range
    else
      all_meetings_in_range
    end

    filtered_meetings.count != 0
  end
end

basic-rails/scheting/app/models/user.rb
class User < ActiveRecord::Base
  include Clearance::User

  has_many :meetings
end

basic-rails/scheting/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Clearance::Controller
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

basic-rails/scheting/app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  authorize_resource
  skip_authorize_resource only: [:edit]

  def index
    @meetings = Meeting.by_date
  end

  def show
    @meeting = Meeting.find(params[:id])
  end

  def new
    @meeting = Meeting.new
  end

  def edit
    @meeting = Meeting.find(params[:id])
    authorize! :edit, @meeting
  end

  def create
    @meeting = current_user.meetings.build(meeting_params)

    if @meeting.save
      redirect_to @meeting, notice: "Successfully created!"
    else
      render 'new'
    end
  end

  def update
    @meeting = Meeting.find(params[:id])

    if @meeting.update(meeting_params)
      redirect_to @meeting, notice: 'Edited!'
    else
      render 'edit'
    end
  end

  def destroy
    Meeting.find(params[:id]).destroy
    redirect_to rooms_path
  end

  private

  def meeting_params
    params.require(:meeting).permit(:title, :begins, :ends, :room_id)
  end
end

basic-rails/scheting/app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  authorize_resource

  def index
    @rooms = Room.all
  end
end

basic-rails/scheting/app/helpers/application_helper.rb
module ApplicationHelper
end

basic-rails/scheting/app/helpers/meetings_helper.rb
module MeetingsHelper
end

basic-rails/scheting/app/helpers/rooms_helper.rb
module RoomsHelper
end

basic-rails/scheting/app/helpers/users_helper.rb
module UsersHelper
end

basic-rails/scheting/app/views/layouts/application.slim
doctype html
html
  head
    title Scheting
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags

  body

    - flash.each do |key, value|
      p = value

    = link_to "Rooms", rooms_path
    span.separator | 
    = link_to 'Users', users_path
    
    - if signed_in? 
      | Signed in as: 
      = current_user.email
      = button_to 'Sign out', sign_out_path, method: :delete
    - else
      = link_to 'Sign in', sign_in_path

    == yield

basic-rails/scheting/app/views/meetings/_form.html.erb
<% meeting.errors.full_messages.each do |message| %>
  <p class="error"><%= message %>
<% end %>

<p>
  <%= f.label :title %>
  <%= f.text_field :title %>
</p>

<p>
  <%= f.label :begins %>
  <%= f.date_select :begins%>
  <%= f.time_select :begins, ignore_date: true %>
</p>

<p>
  <%= f.label :ends %>
  <%= f.date_select :ends%>
  <%= f.time_select :ends, ignore_date: true %>
</p>
<p>
  <%= f.label :room_id %>
  <%= f.select :room_id, options_for_select( Room.all.map { |room| [room.name, room.id] }) %>
</p>
<p>
  <%= f.submit %>
</p>

basic-rails/scheting/app/views/meetings/edit.html.erb
<h1>Editing Meeting</h1>

<%= form_for :meeting, url: meeting_path(@meeting), method: :patch do |f|%>
  <%= render 'form', meeting: @meeting, f: f %>
<% end %>

<%= link_to 'Back', meeting_path(@meeting) %>

basic-rails/scheting/app/views/meetings/index.html.erb
<h1>Meetings</h1>

basic-rails/scheting/app/views/meetings/new.html.erb
<h1>Schedule a meeting</h1>

<%= form_for :meeting, url: meetings_path do |f|%>
  <%= render 'form', meeting: @meeting, f: f %>
<% end %>

basic-rails/scheting/app/views/meetings/show.html.erb
<h1><%= @meeting.title %></h1>

<p>Begins: <%= @meeting.begins %></p>
<p>Ends: <%= @meeting.ends %></p>
<p>User: <%= @meeting.user_id %></p>
<p>Room: <%= @meeting.room_id %></p>

<% if can? :manage, @meeting%>
	<p><%= link_to 'Edit meeting', edit_meeting_path(@meeting) %></p>
	<p><%= link_to 'Delete meeting', meeting_path(@meeting), method: :delete %></p>
<% end %>

basic-rails/scheting/app/views/rooms/index.slim
p = link_to 'New meeting', new_meeting_path 

- @rooms.each do |room|

  h2 = room.name

  h3 Meetings

  table
    tr
      th Meeting
      th Begins
      th ends
      - room.meetings.each do |meeting|
        tr
          td id="#{meeting.id}"
            = link_to meeting.title, meeting_path(meeting)
          td 
            = l meeting.begins, format: :short
          td 
            = l meeting.ends, format: :short
      